// apps/solid/src/app/App.tsx
/* @refresh reload */
import { Route, Router } from "@solidjs/router";
import { type Component, lazy } from "solid-js";

const Counter = lazy(() => import("./Counter"));

const App: Component<{ url?: string }> = ({ url }) => {
	return (
		<Router root={Layout} url={url ? url : ""}>
			<Route path="/" component={() => <h1>Solid</h1>} />
			<Route path="/counter" component={Counter} />
		</Router>
	);
};

const Layout: Component<any> = ({ children }) => {
	return (
		<>
			<ul>
				<li>
					<a href="/">Home</a>
				</li>
				<li>
					<a href="/counter">Counter</a>
				</li>
			</ul>
			{children}
		</>
	);
};

export default App;

// apps/react-router/src/app/App.tsx
import Counter from "./Counter";
import type { FC } from "react";
import { Routes, Route, Link } from "react-router-dom";

const App: FC = () => {
	return (
		<>
			<ul>
				<li>
					<Link to="/">Home</Link>
				</li>
				<li>
					<Link to="/counter">Counter</Link>
				</li>
			</ul>
			<Routes>
				<Route path="/" Component={() => <h1>React Router</h1>} />
				<Route path="/counter" Component={Counter} />
				<Route path="*" Component={() => <h1>Not Found</h1>} />
			</Routes>
		</>
	);
};

export default App;
