// apps/react/src/server/+app.tsx
import App from "@/app";
import { src } from "client:script";
import { StrictMode } from "react";
import { renderToReadableStream } from "react-dom/server.edge";

export default {
	async fetch(_req: Request) {
		return new Response(
			await renderToReadableStream(
				<StrictMode>
					<App />
				</StrictMode>,
				{ bootstrapModules: src.module },
			),
			{
				headers: {
					"content-type": "text/html",
				},
			},
		);
	},
};

// apps/solid/src/server/+app.tsx
import App from "@/app/App";
import { html } from "client:page";
import { renderToString, generateHydrationScript } from "solid-js/web";

export default {
	fetch(req: Request) {
		const appHtml = renderToString(() => <App url={req.url} />);

		if (appHtml) {
			const parts = html.split("%SSR%");

			return new Response(
				[parts[0], generateHydrationScript(), parts[1], appHtml, parts[2]].join(
					"",
				),
				{
					headers: {
						"Content-Type": "text/html",
					},
				},
			);
		}

		return new Response("Not found", { status: 404 });
	},
};
